scaler:
    heroku_app_name: my-heroku-app
    heroku_api_key: <%= ENV['HEROKU_API_KEY'] %>
    #dry_run: true  # Will not actually connect to Heroku in this mode
    interval: 5    # Wake up every 5s to check APIs
    relaxation_period: 300   # Must be at below threshold for at least this long before dropping down a dyno

error_handlers:
    -
        type: Dynosaur::ErrorHandler::Console

controller_plugins:
    -
        name: dynos
        type: Dynosaur::Controllers::DynosControllerPlugin
        interval:
        min_resource: <%= ENV.fetch('MIN_WEB_DYNOS', 2) %>
        max_resource: <%= ENV.fetch('MAX_WEB_DYNOS', 15) %>
        input_plugins:
            -
                name: newrelic
                type: Dynosaur::Inputs::NewRelicPlugin
                interval: 10
                key: <%= ENV["NEW_RELIC_API_KEY"] %>
                app_id: 1234567
                rpm_per_dyno: 400
                hysteresis_period: 60
